import '../db.dart';

// ─────────────────────────────────────────────────────────────────────────────
// 🌱 DoctorSeeder
//
// Seeds the doctors table with 100 real doctors from Dataset.xlsx.
// Usage (call once on first launch):
//
//   await DoctorSeeder.seed();
//
// Idempotent: skips automatically if the table already has rows.
// ─────────────────────────────────────────────────────────────────────────────

class DoctorSeeder {
  DoctorSeeder._();

  static Future<void> seed() async {
    final db = await DB.instance.database;

    // Skip if already seeded
    final rows = await db.rawQuery('SELECT COUNT(*) AS c FROM doctors');
    if ((rows.first['c'] as int) > 0) return;

    // Use a batch for performance — one transaction for all 100 inserts
    final batch = db.batch();

    for (final sql in _insertStatements) {
      batch.execute(sql);
    }

    await batch.commit(noResult: true);
  }

  // ── Raw INSERT statements (auto-generated from Dataset.xlsx) ──────────────
  static const List<String> _insertStatements = [
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Amar Amrani', 'Généraliste', 'Ferdjioua / Mila', '031599030', NULL, 'cité 20 Aout,Ferdjioua,Mila', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Salaheddine KOUITA', 'Généraliste', 'Ferdjioua / Mila', '0697 85 58 21', NULL, 'B.p 235 ferdjioua mila, 43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdellatif AMRANI', 'Généraliste', 'Ferdjioua / Mila', '031599030', NULL, 'b.p 235,Ferdjioua, Mila', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mohamed BENSACI', 'Généraliste', 'Ferdjioua / Mila', '031574691', NULL, 'Cité soumem bloc C n°123 bensaci /a Ferdjioua,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdelouahab BENSACI', 'Généraliste', 'Ferdjioua / Mila', NULL, NULL, 'Ferdjioua,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Oussama HARIKECH', 'Dermatologue', 'Ferdjioua / Mila', '031495151/ 0656 25 03 74', NULL, 'Cité 20 août Ferdjioua Mila', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ahmed BENZOGHLI', 'Chirurgien Orthopédiste Traumatologue', 'Tadjenanet / Mila', '0551 28 24 46', NULL, 'Cabinet medico chirurgical, coopérative El Amel,Tadjenanet 43220 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Azzeddine TENNACHE', 'Généraliste', 'Mila / Mila', '031614124/ 0773692549', NULL, '13,rue Bounakir,cité des frères Borni, ,Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mohamed samy DALICHAOUCH', 'Médecin interniste', 'Mila / Mila', '031405153/ 0699 32 96 95', NULL, 'Cité des 200 logements Telaghma,Telerghma 43250 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdellah BENDRIDI', 'dentiste', 'Mila / Mila', '767547094', NULL, 'Citee boutoute batiment33 2etage 43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Nadia BOUKROUH', 'Endocrinologue', 'Mila / Mila', '058 51 92 80', NULL, 'Citée 500 logts batiment n°1 ESTE MILA,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Aicha IDRAICHA EP SELLAHI', 'Dermatologue', 'Mila / Mila', '031480075/ 0 672 73 50 02', NULL, 'Rue saighi NR 10,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Souhail BELGUECHI', 'Généraliste', 'Ain Melouk / Mila', '031417161/ 0655 39 40 40 / 0557545054', NULL, 'Ain Melouk 43210 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ali BELBEKHOUCHE', 'Psychiatre', 'Mila / Mila', NULL, NULL, 'CITE DES 160 LGTS BT 08 N44,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mohamed BENMAHDJOUB', 'Généraliste', 'BOUHATEM / Mila', NULL, NULL, NULL, 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mohamed BOUSEFSAF', 'Oto-Rhino-Laryngologiste (ORL)', 'Mila / Mila', '031573155', NULL, 'Cité 500 logts,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Yacine ASSIFER', 'Pneumologue', 'Chelghoum Laid / Mila', '031528209', NULL, 'Cité Ouskourt abdelkarim, Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Badis LEBSIR', 'Généraliste', 'Zegaia / Mila', '031554155', NULL, 'Zeghaia 43360 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Belkacem DJEGHBELLOU', 'Généraliste', 'Mila / Mila', '031529854', NULL, '43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Dalila BENDJEDDOU', 'Généraliste', 'Mila / Mila', '031574737', NULL, '20 Rue alliouche nouar, 43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Amar BOUGOUIZI', 'Généraliste', 'Grerem gouga / Mila', '0213564049', NULL, 'Grarem 43100 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Nabil KHELIFI', 'Généraliste', 'Mila / Mila', '031520219', NULL, 'ROUTE N°5 Oued Athmania', 'Chaque jour (9h - 17h), sauf le Vendredi', NULL, NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Yacina BENZIAR', 'Généraliste', 'Ain Beida Horche / Mila', '072173817', NULL, 'Ain Beida Horche, 43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdelazziz BENABDOUN', 'interniste', 'Chelghoum Laid / Mila', '031527573', NULL, 'Cité Ouskkourt NR 27, Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Fouad LAKHLEF ABDENOUR', 'Généraliste', 'Sidi merouane / Mila', '031568745', NULL, 'Sidi Merouane 43150 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mostefa BABA ALI ALI', 'Généraliste', 'Mila / Mila', '031522143', NULL, '21 Rue lahoua A.Rahmane ,Tadjenanet 43220 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mourad BAGOUL', 'Généraliste', 'Grerem gouga / Mila', '031565588', NULL, 'Grarem 43100 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('X RAMDHAN', 'Chirurgien Orthopédiste Traumatologue', 'Chelghoum Laid / Mila', '031526666', NULL, 'Clinique Privée,Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ali TRIKI', 'Généraliste', 'Tadjenanet / Mila', NULL, NULL, 'Tadjenanet 43220 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mourad MANA', 'Généraliste', 'Tadjenanet / Mila', NULL, NULL, 'Cité nouvelle Tadjenant,Tadjenanet 43220 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Slimane BENHACINE', 'Généraliste', 'Chelghoum Laid / Mila', NULL, NULL, 'Cité djemaa lakhdar, Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Belkacem BENMASOUR', 'Généraliste', 'Mila / Mila', '034525904', NULL, 'Mila,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Zouheir MANSAR', 'Généraliste', 'Tadjenanet / Mila', NULL, NULL, 'Cité nouvelle Tadjenant,Tadjenanet 43220 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Amar BOUGHABA', 'Généraliste', 'Grerem gouga / Mila', '031564049', NULL, 'Grarem 43100 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mourad HOUCINET', 'Neurologue', 'Mila / Mila', NULL, NULL, 'CitÚ 500 Logts Bt 89,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Rachi KEDIDA', 'Généraliste', 'Ain Beida Horche / Mila', '031592191', NULL, 'Ain Beida Horche, 43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ali HABOUDJI', 'Généraliste', 'TELAGHMA / Mila', '031561241', NULL, 'TELAGHMA , 43000 Mila Algerie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Chafik DAMAK AHMED', 'Généraliste', 'Mila / Mila', '031460102', NULL, '02 rue SAIGHI med Salah AZZEBA LOTFI,43110', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Farah BOUCHOUCHA', 'Psychiatre', 'Mila / Mila', NULL, NULL, 'CITE BOUTTOUT BT 21 N06,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Med BOUGHIDA', 'Oto-Rhino-Laryngologiste (ORL)', 'Mila / Mila', NULL, NULL, 'RUE SAIGUI,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Youcef BOUHROUR', 'Généraliste', 'Mila / Mila', '031562477', NULL, '43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Hocine BOUSMINA', 'Généraliste', 'Grerem gouga / Mila', '031564255', NULL, 'Grarem 43100 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ammar BOUACID', 'Généraliste', 'Mila / Mila', '031520276', NULL, 'Cité du 1er Novembre n°12 Oued Athmania', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Yamina BAOUCHE', 'Endocrinologue', 'Mila / Mila', '031579847', NULL, '43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Azeddine TENNACHE', 'Généraliste', 'Chelghoum Laid / Mila', '0773 69 25 49', NULL, '10, Cité des Frères Borni,Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Nora BENYAMINA', 'Généraliste', 'Ain Melouk / Mila', NULL, NULL, 'Ain Melouk 43210 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Saida BOUKOURS', 'Généraliste', 'Mila / Mila', NULL, NULL, 'Cité des freres nourouni n°54', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ali BIRACHE', 'Généraliste', 'Chelghoum Laid / Mila', NULL, NULL, 'Cité des freres bourouni', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Zouleikha DJEGHDIR', 'Anesthésiste-Réanimateur', 'Chelghoum Laid / Mila', '031526666', NULL, 'Clinique Privée,Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ouarda SAIDI', 'Généraliste', 'Tadjenanet / Mila', '031522220', NULL, 'CITE NOUVELLE,Tadjenanet 43220 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Rachid YAHIA', 'Généraliste', 'Yahia Beniguecha /Mila', NULL, NULL, 'Yahia Beniguecha,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Amar ABDEDAIM', 'Généraliste', 'Grerem gouga / Mila', '031565588', NULL, 'Rue de l''aln,Grarem 43100 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Malika BIBI', 'Généraliste', 'Mila / Mila', '031560325', NULL, '43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mounir DJAMAA', 'Généraliste', 'Bougherdeine / Mila', NULL, NULL, 'Bougherdeine, 43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Azzedine ABDEDAIM', 'Généraliste', 'Grerem gouga / Mila', '031565588', NULL, 'Grarem 43100 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ali BOUHOUHOU', 'Neurologue', 'Mila / Mila', NULL, NULL, '08, Rue Larbi Bellahar,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Younes BOUSSOUF', 'Généraliste', 'Mila / Mila', '771676379', NULL, 'Cité 500 logements numéro 330,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Kamel BOUKHEDRA', 'Généraliste', 'Tadjenanet/ Mila', NULL, NULL, 'Rue Benaouda Amor,Tadjenanet 43220 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ahmed AYACHI', 'Généraliste', 'TELAGHMA / Mila', NULL, NULL, 'TELAGHMA,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Rabeh BOUSSEKINE', 'Généraliste', 'Ain Beida Horche /Mila', '072216201', NULL, 'Ain Beida Horche,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Aziz BELIMENE', 'Généraliste', 'Rouached / Mila', NULL, NULL, '77 Rue des oliviers,Rouached 43370 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mostapha DADESSI FALLEH', 'Généraliste', 'Mila / Mila', '031522123', NULL, '43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Azeddine TENNACHE', 'Généraliste', 'Chelghoum Laid / Mila', '0773692549', NULL, '10.Rue Mohamed Bounakir , Cité des Frères Borni.', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mounir KERDOUNE', 'Généraliste', 'Mila / Mila', NULL, NULL, 'Bougherdeine Amira Arres', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdelhamid BOUKEZZOULA', 'Généraliste', 'Zegaia / Mila', NULL, NULL, 'Zeghaia 43360 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Achour BELATTAR', 'Généraliste', 'Sidi merouane / Mila', '031568536', NULL, 'Sidi Merouane 43150 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mohamed BENHIZIA', 'Généraliste', 'Zegaia / Mila', '031579519', NULL, 'Zeghaia 43360 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ferhat BOUKEZZOULA', 'Généraliste', 'Grerem gouga / Mila', '031564211', NULL, 'Grarem 43100 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Belkacem ATTIK', 'Généraliste', 'Chelghoum Laid / Mila', '034525904', NULL, 'Rue khelifa,Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mahfoud BOUZRARA', 'Généraliste', 'Oued andja / Mila', '031566037', NULL, 'Oued andja,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mouloud CHIBOUTI', 'Généraliste', 'Oued Athmania / Mila', '031520044', NULL, 'ROUTE N 5 Oued Athmania', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdellah SADRATI', 'Généraliste', 'Tadjenant', '031522303', NULL, 'Sis Rue du stade Tadjenant,Tadjenanet 43220 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Hamza CHAKLIBI', 'Généraliste', 'Mila / Mila', '031525377', NULL, '43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Nora BELMAMIOUNE', 'Généraliste', 'Ain melouk / Mila', NULL, NULL, 'Ain Melouk 43210 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Hassiba BELKHODJA', 'Psychiatre', 'Chelghoum Laid, Mila', '031426255', NULL, 'CITE ZYGHOUD YOUCEF CHELGHOUM LAI', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Akri BENABDELKADER', 'Généraliste', 'Bouhatem / Mila', NULL, NULL, 'Rue mezmiz aissa Bouhatem', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Amar BENZAKRI NÉE BENHANIA', 'Généraliste', 'Oued andja/ Mila', '031566081', NULL, 'Oued andja, 43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ahmed BAIRA', 'Pharmacien', 'Zeghaia / Mila', '031464454', NULL, 'Route principale,Zeghaia 43360 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Aissa BOUSSOUF', 'Généraliste', 'Oued andja / Mila', '031566565', NULL, 'Oued andja,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Selma KENOUCHI', 'dentiste', 'Mila / Mila', '031474997', NULL, 'Cité 20 aout 1955 bloc "C" RCD,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdehafid BENAMIRA', 'Généraliste', 'Rouached / Mila', NULL, NULL, 'El Rouached,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Chaabane BOUSBIA', 'Généraliste', 'Mila / Mila', NULL, NULL, 'Cité bardou Terrai Bainem', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Eddine DJEGHRI SALAH', 'Généraliste', 'Ferdjioua / Mila', NULL, NULL, 'FERDJIOUA,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Farid BOUDJAADA', 'interniste', 'Mila / Mila', '031574543', NULL, 'Cité 300 logts B NR 2 Bt B n°II', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Ramdane BENALOUACHE MOHAMED', 'Chirurgien Généraliste', 'Mila / Mila', NULL, NULL, 'Mila ville,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Fayçal BENKENIDA', 'Oto-Rhino-Laryngologiste (ORL)', 'Chelghoum Laid / Mila', '0771781485', NULL, 'Cité des 24 logements,Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Salim SOLTANE', 'dentiste', 'Chelghoum Laid / Mila', '0676982258', NULL, 'Chelghoum laid a coté de l''eph,Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mostafa RABAHI', 'Généraliste', 'Tadjenanet/ Mila', NULL, NULL, 'Cité nouvelle Tadjenant', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abderrahmane BOUSSABAINE', 'Généraliste', 'Ferdjioua / Mila', '031598477', NULL, 'Ferdjioua, 43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdellah BENDRIDI', 'dentiste', 'Mila / Mila', '0767547094', NULL, 'Citee boutoute batiment33 2etage,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Naima ALI GUECHI', 'Endocrinologue', 'Mila / Mila', '031578873', NULL, 'Cité 500LogtsN°317', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Kamel NAAMOUNE', 'Cardiologue', 'Chelghoum laid / Mila', '031528660', NULL, 'Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Meriem FEDJKHI EP BOULKROUN', 'Cardiologue', 'Mila / Mila', '031579356', NULL, 'Cité 500 logts bloc 2 bt 225', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Eddine MAKHLOUFI SALAH', 'Gynécologue Obstétricien', 'Mila / Mila', '031588566', NULL, 'Cité 48 logts bloc n°1 Bt 03,43000 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Slimane SEGUENI', 'Gynécologue Obstétricien', 'Mila / Mila', NULL, NULL, 'Adresse exacte 23 rue khelifi abderrahmane', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Fouzia BENCHIHEUB EP SELLAHI', 'Gynécologue Obstétricien', 'Mila / Mila', NULL, NULL, 'Cité 500 logts bt 8 bloc 2 n°469', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Mohamed MERBOUHI', 'Néphrologue', 'Chelghoum laid / Mila', '0550 69 87 39', NULL, 'COOPÉRATIVE ESSALEM,Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Abdelghani CHENDER', 'Ophtalmologue', 'Mila / Mila', '031578821', NULL, 'Cite des500 logts bloc 5 n 299', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Salima BOUDJEDDA NÉÉMIHOUB', 'Ophtalmologue', 'Mila / Mila', '031574306', NULL, 'Cite sidi bouyahia bt 2 n14', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
    '''INSERT INTO doctors (name, type, district_commune, phone, email, address, working_hours, appointment_book, gps, social_network, is_available) VALUES ('Djameleddine BENCHEIKH EL HOCINE', 'Ophtalmologue', 'Chelghoum laid / Mila', NULL, NULL, 'Chelghoum Laid 43200 Mila Algérie', 'Chaque jour (9h - 17h), sauf le Vendredi', 'Téléphone, surplace', NULL, NULL, 0)''',
  ];
}
